"""
Base strategy abstract class for all trading strategies.

All trading strategies must inherit from this class and implement
the required abstract methods.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
import logging
from typing import Optional

logger = logging.getLogger(__name__)


class SignalType(Enum):
    """Trading signal types."""

    BUY = "BUY"
    SELL = "SELL"
    HOLD = "HOLD"


@dataclass
class Signal:
    """Represents a trading signal generated by a strategy."""

    symbol: str
    signal_type: SignalType
    confidence: float  # 0.0 - 1.0
    timestamp: datetime = field(default_factory=datetime.utcnow)
    metadata: dict = field(default_factory=dict)

    def __post_init__(self) -> None:
        if not 0.0 <= self.confidence <= 1.0:
            raise ValueError(
                f"Confidence must be between 0.0 and 1.0, got {self.confidence}"
            )

    def __repr__(self) -> str:
        return (
            f"Signal({self.symbol}, {self.signal_type.value}, "
            f"confidence={self.confidence:.2f}, ts={self.timestamp.isoformat()})"
        )


@dataclass
class PositionSize:
    """Represents a calculated position size."""

    symbol: str
    quantity: float
    max_risk_amount: float
    rationale: str

    def __repr__(self) -> str:
        return (
            f"PositionSize({self.symbol}, qty={self.quantity}, "
            f"max_risk={self.max_risk_amount:.2f})"
        )


class BaseStrategy(ABC):
    """
    Abstract base class for all trading strategies.

    All strategies must:
    - Generate signals only (never place orders directly)
    - Validate their own parameters
    - Log all significant events
    - Handle missing or invalid data gracefully

    Example:
        class MyStrategy(BaseStrategy):
            def generate_signals(self, data):
                ...
    """

    def __init__(self, name: str, parameters: dict) -> None:
        """
        Initialize the strategy.

        Args:
            name: Human-readable strategy name.
            parameters: Strategy-specific configuration parameters.
        """
        self.name = name
        self.parameters = parameters
        self._is_enabled = True
        self.validate_parameters()
        logger.info(f"Strategy '{self.name}' initialized with parameters: {parameters}")

    @abstractmethod
    def generate_signals(self, data: object) -> list[Signal]:
        """
        Generate trading signals based on market data.

        Args:
            data: Market data (DataFrame or similar structure).

        Returns:
            List of Signal objects. Empty list means no action.

        Note:
            This method must NEVER place orders. It only generates signals.
        """

    @abstractmethod
    def calculate_position_size(
        self,
        signal: Signal,
        portfolio_value: float,
        current_price: float,
    ) -> PositionSize:
        """
        Calculate the appropriate position size for a signal.

        Args:
            signal: The trading signal to size.
            portfolio_value: Current total portfolio value in USD.
            current_price: Current market price of the symbol.

        Returns:
            PositionSize object with calculated quantity and risk metrics.
        """

    @abstractmethod
    def validate_parameters(self) -> None:
        """
        Validate strategy parameters on initialization.

        Raises:
            ValueError: If any parameter is invalid or out of acceptable range.
        """

    def enable(self) -> None:
        """Enable the strategy."""
        self._is_enabled = True
        logger.info(f"Strategy '{self.name}' enabled.")

    def disable(self) -> None:
        """Disable the strategy."""
        self._is_enabled = False
        logger.warning(f"Strategy '{self.name}' disabled.")

    @property
    def is_enabled(self) -> bool:
        """Return whether the strategy is currently enabled."""
        return self._is_enabled

    def __repr__(self) -> str:
        return (
            f"{self.__class__.__name__}(name='{self.name}', "
            f"enabled={self._is_enabled})"
        )
